/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_longjoy_catskay_jinlearn_MainActivity */

#ifndef _Included_com_longjoy_catskay_jinlearn_MainActivity
#define _Included_com_longjoy_catskay_jinlearn_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_longjoy_catskay_jinlearn_MainActivity
 * Method:    getNativeStringC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring
JNICALL Java_com_longjoy_catskay_jinlearn_MainActivity_getNativeStringC
        (JNIEnv *, jclass);

/*
 * Class:     com_longjoy_catskay_jinlearn_MainActivity
 * Method:    updateFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_com_longjoy_catskay_jinlearn_MainActivity_updateFile
(JNIEnv * , jclass , jstring );

#ifdef __cplusplus
}
#endif
#endif
